FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl git gcc \
    libgl1 \
    libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1

RUN pip install --no-cache-dir ultralytics fastapi uvicorn[standard] python-multipart

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
